# Generated by Django 4.0.3 on 2022-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devicedused',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mayn', models.CharField(blank=True, max_length=100)),
                ('sekond', models.CharField(blank=True, max_length=100)),
                ('brando', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Digitaltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tda', models.CharField(blank=True, max_length=100)),
                ('reso', models.CharField(blank=True, max_length=100)),
                ('orient', models.CharField(blank=True, max_length=100)),
                ('nameart', models.CharField(blank=True, max_length=100)),
                ('prays', models.IntegerField(blank=True)),
                ('curr', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submisyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnam', models.CharField(blank=True, max_length=100)),
                ('emayl', models.CharField(blank=True, max_length=100)),
                ('seks', models.CharField(blank=True, max_length=100)),
                ('countri', models.CharField(blank=True, max_length=100)),
                ('descr', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
